# vim:set syntax=zsh
export ANDROID_HOME=$HOME/.Android/Sdk/
export EDITOR=nvim
export LESS=-Ri
export QT_LOGGING_RULES=qt.svg.warning=false
export PATH=$HOME/.local/bin:$PATH
export PATH=$PATH:$HOME/.local/share/flutter/bin
export PYTHONPATH=$PYTHONPATH:$HOME/Documents/Code/Python
export QT_QPA_PLATFORMTHEME=qt5ct
export NODE_PATH=$HOME/.node_modules
export RIPGREP_CONFIG_PATH=$HOME/.config/ripgrep.conf
